name: Django Tests

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    services:
        db:
          image: mysql:5.7
          env:
            MYSQL_ROOT_PASSWORD: moss123
            MYSQL_DATABASE: seat
          ports:
            - 3306:3306
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
  
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Apply database migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate

    - name: Coverage report
      run: |
        pip install coverage
        coverage run manage.py test
        coverage report